### PR TITLE
Updates webR quarto extension to fix problem

### LINKED ISSUE #304: [Bug]: webr problems on stable and dev version
### What happened?

webr is not wroking and the attched error appears.

Example for one of the outputs  https://insightsengineering.github.io/tlg-catalog/stable

OJS Error
wf: Error in `mount(mountpoint, data_url)`: Can't download Emscripten filesystem image metadata.

Image

### Relevant log output

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [x] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [x] I agree to follow this project's Security Policy.

### PR DESCRIPTION
**Pull request by averissimo**
- Fixes #304 

##### Changes description

- Updates quarto extension

### CODE REVIEW

**Comment by averissimo** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by averissimo** [comment]
There are a bunch of snapshots failing both in `main` (triggered a manual [check that is failing here](https://github.com/insightsengineering/tlg-catalog/actions/runs/14405224492/job/40400039051)) and in this PR.

There are (at least) 3 types of snapshot failures:
- `denom = "n"` just like the one below
- Differences in spacing
- `.labels` not assigning the correct `stat` name _(fixed in this PR)_

```diff
  ── Failure ('test-tables-lab-results-lbt14.R:1:1'): tables/lab-results/lbt14.qmd result_v1 stable ──
  Snapshot of code has changed (variant 'stable'):
  old[10:65] vs new[10:65]
                    Not High                        134 (100%)   134 (100%)     132 (100%)  
      C-Reactive Protein Measurement                                                        
            Not High                                   114          112            115      
  -                 Not High                        45 (33.6%)   55 (41.0%)     57 (43.2%)  
  +                 Not High                        45 (39.5%)   55 (49.1%)     57 (49.6%)  
  -                 1                               18 (13.4%)   18 (13.4%)     19 (14.4%)  
  +                 1                               18 (15.8%)   18 (16.1%)     19 (16.5%)  
  -                 2                               19 (14.2%)   10 (7.5%)      11 (8.3%)   
  +                 2                               19 (16.7%)   10 (8.9%)      11 (9.6%)   
  -                 3                               22 (16.4%)   13 (9.7%)      20 (15.2%)  
  +                 3                               22 (19.3%)   13 (11.6%)     20 (17.4%)  
  -                 4                               10 (7.5%)    16 (11.9%)      8 (6.1%)   
  +                 4                               10 (8.8%)    16 (14.3%)      8 (7.0%)   
            1                                           8            10             7       
  -                 Not High                         5 (3.7%)     2 (1.5%)       2 (1.5%)   
  +                 Not High                        5 (62.5%)    2 (20.0%)      2 (28.6%)   
```

Should the different snapshots be accepted, or should we use `denom = "N_col"` in the code? @insightsengineering/nest-sme ?

**Comment by edelarua** [comment]
> Should the different snapshots be accepted, or should we use `denom = "N_col"` in the code?

You can accept the changes as is. Thanks!

File: package/tests/testthat/setup.R [hunk 1]
```diff
@@ -12,7 +12,7 @@ Sys.setenv("TLG_CATALOG_PKG_TEST_DATA_PATH" = normalizePath(test_data_path))
 # (iv) run `devtools::test(filter = "<article_name>")`
 if_book_exists <- file.exists(test_book_path)
 if_render_book <- FALSE # Remember to change this to FALSE if you want to render articles (otherwise loop)
-if_render_articles <- FALSE
+if_render_articles <- TRUE
```
Comment (pawelru) [inline package/tests/testthat/setup.R:15]: testing leftover?

**Review by pawelru — APPROVED** [review]
Thanks! Does that really solves that issue about xfun?

File: package/tests/testthat/setup.R (hunk 1 above)
Comment (averissimo) [reply package/tests/testthat/setup.R:15]:
```suggestion
if_render_articles <- FALSE
```

**Comment by averissimo** [comment]
I believe so, in my local tests, the issue is gone.
